services:
  nifi:
    image: apache/nifi:2.0.0-M4
    ports:
      - 8443:8443
    restart: unless-stopped
    volumes:
      - ./vastdb_nifi-1.0.2-linux-x86_64-py39.nar:/opt/nifi/nifi-current/nar_extensions/
    environment:
      NIFI_WEB_PROXY_HOST: localhost:8080, vastdb-ingest:8080
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: 123456123456

  traefik:
    image: traefik:v3.1
    ports:
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
        #command:
        #  - --providers.docker
        #  - --entrypoints.web.address=:8080
    restart: unless-stopped
    depends_on:
      - nifi
