services:

  nifi:
    image: apache/nifi:2.0.0-M4
    platform: linux/amd64
    ports:
      - "8443:8443"
    restart: unless-stopped
    volumes:
      - ${PWD}/nar/vastdb_nifi-linux-x86_64-py39.nar:/opt/nifi/nifi-current/nar_extensions/vastdb_nifi-linux-x86_64-py39.nar
    environment:
      NIFI_WEB_PROXY_HOST: ${EXT_HOST}
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: 123456123456
      EXT_HOST: ${EXT_HOST}
    depends_on:
      - download_vastdb_nar

  download_vastdb_nar:
    image: debian:bullseye-slim
    platform: linux/amd64
    volumes:
      - ./nar:/data
    entrypoint: >
      bash -c '
      apt-get update -qq && apt-get install -y wget -qq jq && \
      echo "Fetching latest release..." && \
      LATEST_RELEASE=$$(wget -qO- https://api.github.com/repos/vast-data/vastdb_nifi/releases/latest | jq -r .tag_name | sed "s/^v//") && \
      echo "Latest release is: $$LATEST_RELEASE"
      if [ -n "$$LATEST_RELEASE" ]; then
        echo "Downloading NAR file..." && \
        wget -q --show-progress --continue -O /data/vastdb_nifi-linux-x86_64-py39.nar https://github.com/vast-data/vastdb_nifi/releases/download/v$$LATEST_RELEASE/vastdb_nifi-$$LATEST_RELEASE-linux-x86_64-py39.nar && \
        echo $$LATEST_RELEASE > /data/vastdb_nifi-linux-x86_64-py39.ver && \
        echo "Successfully downloaded NAR file to local folder ./nar"
      else
        echo "Failed to fetch latest release. Exiting." && \
        exit 1
      fi
      '
