services:
  nifi:
    image: apache/nifi:2.0.0-M4
    platform: linux/amd64
    ports:
      - "8443:8443"
    restart: no
    volumes:
      - ./nar/vastdb_nifi-linux-x86_64-py39.nar:/opt/nifi/nifi-current/nar_extensions/
    uts: host
    environment:
      NIFI_WEB_PROXY_HOST: localhost:9443
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: 123456123456
    depends_on:
      - download_vastdb_nar
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-https.entrypoints=websecure
      - traefik.http.routers.traefik-https.rule=Host(`vastdb-ingest`)
      - traefik.http.services.my-service.loadbalancer.server.scheme=https
      - traefik.http.services.my-service.loadbalancer.server.port=8443

  traefik:
    image: traefik:v3.1
    platform: linux/amd64
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--serverstransport.insecureskipverify=true"
    restart: no
    depends_on:
      - nifi

  download_vastdb_nar:
    image: debian:bullseye-slim
    platform: linux/amd64
    volumes:
      - ./nar:/data
    entrypoint: >
      bash -c '
      apt-get update && apt-get install -y curl jq &&
      echo "Fetching latest release..." &&
      LATEST_RELEASE=$$(curl -s https://api.github.com/repos/vast-data/vastdb_nifi/releases/latest | jq -r .tag_name | sed "s/^v//") &&
      echo "Latest release is: $$LATEST_RELEASE" &&
      if [ -n "$$LATEST_RELEASE" ]; then
        echo "Downloading NAR file..." &&
        curl -L -o /data/vastdb_nifi-$$LATEST_RELEASE-linux-x86_64-py39.nar https://github.com/vast-data/vastdb_nifi/releases/download/v$$LATEST_RELEASE/vastdb_nifi-$$LATEST_RELEASE-linux-x86_64-py39.nar &&
        ln -s vastdb_nifi-linux-x86_64-py39.nar vastdb_nifi-$$LATEST_RELEASE-linux-x86_64-py39.nar
        echo "Successfully downloaded NAR file to local folder ./nar"
      else
        echo "Failed to fetch latest release. Exiting." &&
        exit 1
      fi
      '
