http:
  routers:
    nifi:
      entrypoints:
        - websecure
      rule:
        Host: vastdb-ingest
      service: nifi
      middlewares:
        - addforwardheaders@never

  middlewares:
    addforwardheaders:
      headers:
        X-Forwarded-Host:
          - expr: replace(http.host, '^.*$', '$1')  # Replace host header
        X-Forwarded-Port:
          - expr: replace(http.port, '^.*$', '$1')  # Replace port header
        X-Forwarded-Proto:
          - expr: replace(http.scheme, '^.*$', '$1')  # Replace scheme header

tls:
  stores:
    default:
      defaultCertificate:
        certFile: ""
        keyFile: ""

log:
  filePath: "./traefik.log"
