http:
  routers:
    nifi:
      entrypoints:
        - web
      rule: "Host(`vastdb-ingest`, `localhost`)"
      service: nifi
      middlewares:
        - addforwardheaders

  services:
    nifi:
      loadbalancer:
        servers:
          - url: "https://nifi-vast-nifi-docker-compose:8443"

  middlewares:
    addforwardheaders:
      headers:
        X-Forwarded-Host:
          - expr: "localhost"
        X-Forwarded-Port:
          - expr: "8443"
        X-Forwarded-Proto:
          - expr: "https"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: ""
        keyFile: ""

log:
  level: DEBUG

accessLog:
  filePath: "/var/log/access.log"

entryPoints:
  web:
    address: ":8080"

providers:
  docker:
    useBindPortIP: true

